#!/usr/bin/python3

import parser

flag_utf8 = False
mode_read = 'args'

for char in parser.jelly.sys.argv[1]:
	if char == 'f':
		flag_file = True
	elif char == 'u':
		flag_utf8 = True
	elif char == 'e':
		flag_file = False
	elif char == 'c':
		mode_read = 'char'
		flag_iout = True

if flag_file:
	with open(parser.jelly.sys.argv[2], 'rb') as file:
		code = file.read()
	if flag_utf8:
		code = ''.join([char for char in code.decode('utf-8').replace('\n', '¶') if char in parser.code_page])
	else:
		code = ''.join([parser.code_page[i] for i in code])
else:
	code = parser.jelly.sys.argv[2]
	if flag_utf8:
		code = ''.join([char for char in code.replace('\n', '¶') if char in parser.code_page])
	else:
		code = ''.join([parser.code_page[ord(i)] for i in code])

args = tuple(map(parser.jelly.helper.try_eval, parser.jelly.sys.argv[3:]))

for index in range(min(5, len(args))):
	parser.jelly.atoms['³⁴⁵⁶⁷'[index]].call = lambda literal = args[index]: literal

if mode_read == 'char':
	while True:
		char = parser.jelly.sys.stdin.read(1)
		if char == '':
			break
		output = parser.jelly.variadic_chain(parser.parse_code(code)[-1], char)
		if flag_iout:
			print(output, end = '')
else:
	print(parser.jelly.helper.stringify(parser.jelly.variadic_chain(parser.parse_code(code)[-1], args[:2])), end = '')