#!/usr/bin/python3

import parser, sys

char_table = ''.join(sorted(set(''.join(map(chr,range(0, 128))) + parser.str_allchar)))

assert(len(char_table) <= 256)

with open(sys.argv[2], 'rb') as file:
	code = file.read()

if 'u' in sys.argv[1]:
	code = code.decode()
	for char in code:
		assert(char in char_table)
else:
	code = ''.join([char_table[i] for i in code])

args = tuple(map(parser.jelly.ast.literal_eval, sys.argv[3:]))

print(parser.jelly.variadic_chain(parser.parse_code(code)[-1], args), end = '')